neuroml2_site_may1614/config/routes.rb
# Redmine - project management software
# Copyright (C) 2006-2013  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

RedmineApp::Application.routes.draw do
  root :to => 'welcome#index', :as => 'home'
  match 'home', :to => 'welcome#index', :as => 'home'
  match 'neuromlv2', :to => 'welcome#neuromlv2', :as => 'neuromlv2'
  match 'alpha_schema', :to => 'welcome#alpha_schema' , :as => 'alpha_schema'
  match 'extend_neuroml', :to => 'welcome#extend_neuroml', :as => 'extend_neuroml'
  match 'lems', :to => 'welcome#lems', :as => 'lems'
  match 'relevant_publications', :to => 'welcome#relevant_publications', :as => 'relevant_publications'
  match 'workshops', :to => 'welcome#workshops', :as => 'workshops'
  
  match 'tool_support', :to => 'welcome#tool_support', :as => 'tool_support'
  match 'validate', :to => 'welcome#validate', :as => 'validate'
  match 'neuron_tools', :to => 'welcome#neuron_tools', :as => 'neuron_tools'
  match 'pynn', :to => 'welcome#pynn', :as => 'pynn'
  match 'x3dtools', :to => 'welcome#x3dtools', :as => 'x3dtools'

  match 'browse_models', :to => 'welcome#browse_models', :as => 'browse_models'
  match 'model_submit', :to => 'welcome#model_submit', :as => 'model_submit'
  match 'add_cell', :to => 'welcome#add_cell', :as => 'add_cell'
  match 'add_model', :to => 'welcome#add_model', :as => 'add_model'
  match 'search_result', :to => 'welcome#search_result', :as => 'search_result'
  match 'search_process_test', :to => 'welcome#search_process_test', :as => 'search_process_test'
  match 'search_process', :to => 'welcome#search_process', :as => 'search_process'
  match 'search_python', :to => 'welcome#search_python', :as => 'search_python'
  match 'model_info', :to => 'welcome#model_info', :as => 'model_info'
  match 'submission', :to => 'welcome#submission', :as => 'submission'
  match 'submission_error' , :to => 'welcome#submission_error', :as => 'submission_error'

  match 'history', :to => 'welcome#history', :as => 'history'
  match 'editors', :to => 'welcome#editors', :as => 'editorial_board'
  match 'sitemap', :to => 'welcome#sitemap', :as => 'sitemap'
  match 'scientific_committee', :to => 'welcome#scientific_committee', :as => 'scientific_committee'
  match 'acknowledgements', :to => 'welcome#acknowledgements', :as => 'acknowledgements'
  
  match 'introduction', :to => 'welcome#introduction', :as => 'introduction'
  match 'newsevents', :to => 'welcome#newsevents', :as => 'newsevents'
  match 'workshop2012', :to => 'welcome#workshop2012', :as => 'workshop2012'
  match 'workshop2011', :to => 'welcome#workshop2011', :as => 'workshop2011'
  match 'workshop2010', :to => 'welcome#workshop2010', :as => 'workshop2010'
  match 'workshop2009', :to => 'welcome#workshop2009', :as => 'workshop2009'
  match 'CNS_workshop', :to => 'welcome#CNS_workshop', :as => 'CNS_workshop'
  match 'lems_dev', :to => 'welcome#lems_dev', :as => 'lems_dev'
  match 'libnml', :to => 'welcome#libnml', :as => 'libnml'
  match 'compatibility', :to => 'welcome#compatibility', :as => 'compatibility'
  match 'specifications', :to => 'welcome#specifications', :as => 'specifications'
  match 'examples', :to => 'welcome#examples', :as => 'examples'
  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put]
  match '/issues/preview/new/:project_id', :to => 'previews#issue', :as => 'preview_new_issue', :via => [:get, :post, :put]
  match '/issues/preview/edit/:id', :to => 'previews#issue', :as => 'preview_edit_issue', :via => [:get, :post, :put]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put]

  match 'projects/:id/wiki', :to => 'wikis#edit', :via => :post
  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  match '/journals/diff/:id', :to => 'journals#diff', :id => /\d+/, :via => :get
  match '/journals/edit/:id', :to => 'journals#edit', :id => /\d+/, :via => [:get, :post]

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  match 'my/reset_rss_key', :controller => 'my', :action => 'reset_rss_key', :via => :post
  match 'my/reset_api_key', :controller => 'my', :action => 'reset_api_key', :via => :post
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/page_layout', :controller => 'my', :action => 'page_layout', :via => :get
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post

  resources :users
  match 'users/:id/memberships/:membership_id', :to => 'users#edit_membership', :via => :put, :as => 'user_membership'
  match 'users/:id/memberships/:membership_id', :to => 'users#destroy_membership', :via => :delete
  match 'users/:id/memberships', :to => 'users#edit_membership', :via => :post, :as => 'user_memberships'

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
    end

    resources :memberships, :shallow => true, :controller => 'members', :only => [:index, :show, :new, :create, :update, :destroy] do
      collection do
        get 'autocomplete'
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create] do
      resources :time_entries, :controller => 'timelog' do
        collection do
          get 'report'
        end
      end
    end
    # issue form update
    match 'issues/update_form', :controller => 'issues', :action => 'update_form', :via => [:put, :post], :as => 'issue_form'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end

neuroml2_site_may1614/app/helpers/my_helper.rb
# encoding: utf-8
#
# Redmine - project management software
# Copyright (C) 2006-2013  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module MyHelper
  def calendar_items(startdt, enddt)
    Issue.visible.
      where(:project_id => User.current.projects.map(&:id)).
      where("(start_date>=? and start_date<=?) or (due_date>=? and due_date<=?)", startdt, enddt, startdt, enddt).
      includes(:project, :tracker, :priority, :assigned_to).
      all
  end

  def documents_items
    Document.visible.order("#{Document.table_name}.created_on DESC").limit(10).all
  end

  def issuesassignedtome_items
    Issue.visible.open.
      where(:assigned_to_id => ([User.current.id] + User.current.group_ids)).
      limit(10).
      includes(:status, :project, :tracker, :priority).
      order("#{IssuePriority.table_name}.position DESC, #{Issue.table_name}.updated_on DESC").
      all
  end

  def issuesreportedbyme_items
    Issue.visible.
      where(:author_id => User.current.id).
      limit(10).
      includes(:status, :project, :tracker).
      order("#{Issue.table_name}.updated_on DESC").
      all
  end

  def issueswatched_items
    Issue.visible.on_active_project.watched_by(User.current.id).recently_updated.limit(10).all
  end

  def news_items
    News.visible.
      where(:project_id => User.current.projects.map(&:id)).
      limit(10).
      includes(:project, :author).
      order("#{News.table_name}.created_on DESC").
      all
  end

  def timelog_items
    TimeEntry.
      where("#{TimeEntry.table_name}.user_id = ? AND #{TimeEntry.table_name}.spent_on BETWEEN ? AND ?", User.current.id, Date.today - 6, Date.today).
      includes(:activity, :project, {:issue => [:tracker, :status]}).
      order("#{TimeEntry.table_name}.spent_on DESC, #{Project.table_name}.name ASC, #{Tracker.table_name}.position ASC, #{Issue.table_name}.id ASC").
      all
  end
end

neuroml2_site_may1614/app/views/my/_block.html.erb
<div id="block_<%= block_name.dasherize %>" class="mypage-box">

    <div style="float:right;margin-right:16px;z-index:500;">
    <%= link_to "", {:action => "remove_block", :block => block_name}, :method => 'post', :class => "close-icon" %>
    </div>

    <div class="handle">
    <%= render :partial => "my/blocks/#{block_name}", :locals => { :user => user } %>
    </div>
</div>

neuroml2_site_may1614/app/views/my/_sidebar.html.erb
<h3><%=l(:label_my_account)%></h3>

<p><%=l(:field_login)%>: <strong><%= link_to_user(@user, :format => :username) %></strong><br />
<%=l(:field_created_on)%>: <%= format_time(@user.created_on) %></p>

<% if @user.own_account_deletable? %>
  <p><%= link_to(l(:button_delete_my_account), {:action => 'destroy'}, :class => 'icon icon-del') %></p>
<% end %>

<h4><%= l(:label_feeds_access_key) %></h4>

<p>
<% if @user.rss_token %>
<%= l(:label_feeds_access_key_created_on, distance_of_time_in_words(Time.now, @user.rss_token.created_on)) %>
<% else %>
<%= l(:label_missing_feeds_access_key) %>
<% end %>
(<%= link_to l(:button_reset), {:action => 'reset_rss_key'}, :method => :post %>)
</p>

<% if Setting.rest_api_enabled? %>
<h4><%= l(:label_api_access_key) %></h4>
<div>
  <%= link_to_function(l(:button_show), "$('#api-access-key').toggle();")%>
  <pre id='api-access-key' class='autoscroll'><%= h(@user.api_key) %></pre>
</div>
<%= javascript_tag("$('#api-access-key').hide();") %>
<p>
<% if @user.api_token %>
<%= l(:label_api_access_key_created_on, distance_of_time_in_words(Time.now, @user.api_token.created_on)) %>
<% else %>
<%= l(:label_missing_api_access_key) %>
<% end %>
(<%= link_to l(:button_reset), {:action => 'reset_api_key'}, :method => :post %>)
</p>
<% end %>

neuroml2_site_may1614/app/views/my/account.html.erb
<div class="contextual">
<%= link_to(l(:button_change_password), {:action => 'password'}, :class => 'icon icon-passwd') if @user.change_password_allowed? %>
<%= call_hook(:view_my_account_contextual, :user => @user)%>
</div>

<h2><%=l(:label_my_account)%></h2>
<%= error_messages_for 'user' %>

<%= labelled_form_for :user, @user,
                     :url => { :action => "account" },
                     :html => { :id => 'my_account_form',
                                :method => :post } do |f| %>
<div class="splitcontentleft">
<fieldset class="box tabular">
  <legend><%=l(:label_information_plural)%></legend>
  <p><%= f.text_field :firstname, :required => true %></p>
  <p><%= f.text_field :lastname, :required => true %></p>
  <p><%= f.text_field :mail, :required => true %></p>
  <p><%= f.select :language, lang_options_for_select %></p>
  <% if Setting.openid? %>
  <p><%= f.text_field :identity_url  %></p>
  <% end %>

  <% @user.custom_field_values.select(&:editable?).each do |value| %>
    <p><%= custom_field_tag_with_label :user, value %></p>
  <% end %>
  <%= call_hook(:view_my_account, :user => @user, :form => f) %>
</fieldset>

<%= submit_tag l(:button_save) %>
</div>

<div class="splitcontentright">
<fieldset class="box">
  <legend><%=l(:field_mail_notification)%></legend>
  <%= render :partial => 'users/mail_notifications' %>
</fieldset>

<fieldset class="box tabular">
  <legend><%=l(:label_preferences)%></legend>
  <%= render :partial => 'users/preferences' %>
</fieldset>

</div>
<% end %>

<% content_for :sidebar do %>
<%= render :partial => 'sidebar' %>
<% end %>

<% html_title(l(:label_my_account)) -%>

neuroml2_site_may1614/app/views/my/destroy.html.erb
<h2><%=l(:label_confirmation)%></h2>
<div class="warning">
<p><%= simple_format l(:text_account_destroy_confirmation)%></p>
<p>
    <%= form_tag({}) do %>
    <label><%= check_box_tag 'confirm', 1 %> <%= l(:general_text_Yes) %></label>
    <%= submit_tag l(:button_delete_my_account) %> |
		<%= link_to l(:button_cancel), :action => 'account' %>
    <% end %>
</p>
</div>

neuroml2_site_may1614/app/views/my/page.html.erb
<div class="contextual">
    <%= link_to l(:label_personalize_page), :action => 'page_layout' %>
</div>

<h2><%=l(:label_my_page)%></h2>

<div id="list-top">
  <% @blocks['top'].each do |b|
     next unless MyController::BLOCKS.keys.include? b  %>
  <div class="mypage-box">
    <%= render :partial => "my/blocks/#{b}", :locals => { :user => @user } %>
  </div>
  <% end if @blocks['top'] %>
</div>

<div id="list-left" class="splitcontentleft">
  <% @blocks['left'].each do |b|
     next unless MyController::BLOCKS.keys.include? b %>
  <div class="mypage-box">
    <%= render :partial => "my/blocks/#{b}", :locals => { :user => @user } %>
  </div>
  <% end if @blocks['left'] %>
</div>

<div id="list-right" class="splitcontentright">
  <% @blocks['right'].each do |b|
     next unless MyController::BLOCKS.keys.include? b %>
  <div class="mypage-box">
    <%= render :partial => "my/blocks/#{b}", :locals => { :user => @user } %>
  </div>
  <% end if @blocks['right'] %>
</div>

<%= context_menu issues_context_menu_path %>

<% html_title(l(:label_my_page)) -%>

neuroml2_site_may1614/app/views/my/page_layout.html.erb
<div class="contextual">
<% if @block_options.present? %>
  <%= form_tag({:action => "add_block"}, :id => "block-form") do %>
  <%= label_tag('block-select', l(:label_my_page_block)) %>:
  <%= select_tag 'block',
                 content_tag('option') + options_for_select(@block_options),
                 :id => "block-select" %>
  <%= link_to l(:button_add), '#', :onclick => '$("#block-form").submit()', :class => 'icon icon-add' %>
  <% end %>
<% end %>
<%= link_to l(:button_back), {:action => 'page'}, :class => 'icon icon-cancel' %>
</div>

<h2><%=l(:label_my_page)%></h2>

<div id="list-top" class="block-receiver">
  <% @blocks['top'].each do |b|
     next unless MyController::BLOCKS.keys.include? b %>
  <%= render :partial => 'block', :locals => {:user => @user, :block_name => b} %>
  <% end if @blocks['top'] %>
</div>

<div id="list-left" class="splitcontentleft block-receiver">
  <% @blocks['left'].each do |b|
     next unless MyController::BLOCKS.keys.include? b %>
  <%= render :partial => 'block', :locals => {:user => @user, :block_name => b} %>
  <% end if @blocks['left'] %>
</div>

<div id="list-right" class="splitcontentright block-receiver">
  <% @blocks['right'].each do |b|
     next unless MyController::BLOCKS.keys.include? b %>
  <%= render :partial => 'block', :locals => {:user => @user, :block_name => b} %>
  <% end if @blocks['right'] %>
</div>

<%= javascript_tag "initMyPageSortable('top', '#{ escape_javascript url_for(:action => "order_blocks", :group => "top") }');" %>
<%= javascript_tag "initMyPageSortable('left', '#{ escape_javascript url_for(:action => "order_blocks", :group => "left") }');" %>
<%= javascript_tag "initMyPageSortable('right', '#{ escape_javascript url_for(:action => "order_blocks", :group => "right") }');" %>

<% html_title(l(:label_my_page)) -%>

neuroml2_site_may1614/app/views/my/password.html.erb
<h2><%=l(:button_change_password)%></h2>

<%= error_messages_for 'user' %>

<%= form_tag({}, :class => "tabular") do %>
<div class="box">
<p><label for="password"><%=l(:field_password)%> <span class="required">*</span></label>
<%= password_field_tag 'password', nil, :size => 25 %></p>

<p><label for="new_password"><%=l(:field_new_password)%> <span class="required">*</span></label>
<%= password_field_tag 'new_password', nil, :size => 25 %>
<em class="info"><%= l(:text_caracters_minimum, :count => Setting.password_min_length) %></em></p>

<p><label for="new_password_confirmation"><%=l(:field_password_confirmation)%> <span class="required">*</span></label>
<%= password_field_tag 'new_password_confirmation', nil, :size => 25 %></p>
</div>
<%= submit_tag l(:button_apply) %>
<% end %>

<% content_for :sidebar do %>
<%= render :partial => 'sidebar' %>
<% end %>