neuroml2_site_may1614/config/routes.rb
  match 'validate', :to => 'welcome#validate', :as => 'validate'
  match 'neuron_tools', :to => 'welcome#neuron_tools', :as => 'neuron_tools'
  match 'pynn', :to => 'welcome#pynn', :as => 'pynn'
  match 'x3dtools', :to => 'welcome#x3dtools', :as => 'x3dtools'

  match 'browse_models', :to => 'welcome#browse_models', :as => 'browse_models'
  match 'model_submit', :to => 'welcome#model_submit', :as => 'model_submit'
  match 'add_cell', :to => 'welcome#add_cell', :as => 'add_cell'
  match 'add_model', :to => 'welcome#add_model', :as => 'add_model'
  match 'search_result', :to => 'welcome#search_result', :as => 'search_result'
  match 'search_process_test', :to => 'welcome#search_process_test', :as => 'search_process_test'
  match 'search_process', :to => 'welcome#search_process', :as => 'search_process'
  match 'search_python', :to => 'welcome#search_python', :as => 'search_python'
  match 'model_info', :to => 'welcome#model_info', :as => 'model_info'
  match 'submission', :to => 'welcome#submission', :as => 'submission'
  match 'submission_error' , :to => 'welcome#submission_error', :as => 'submission_error'

  match 'history', :to => 'welcome#history', :as => 'history'
  match 'editors', :to => 'welcome#editors', :as => 'editorial_board'
  match 'sitemap', :to => 'welcome#sitemap', :as => 'sitemap'
  match 'scientific_committee', :to => 'welcome#scientific_committee', :as => 'scientific_committee'
  match 'acknowledgements', :to => 'welcome#acknowledgements', :as => 'acknowledgements'
  
  match 'introduction', :to => 'welcome#introduction', :as => 'introduction'
  match 'newsevents', :to => 'welcome#newsevents', :as => 'newsevents'
  match 'workshop2012', :to => 'welcome#workshop2012', :as => 'workshop2012'
  match 'workshop2011', :to => 'welcome#workshop2011', :as => 'workshop2011'
  match 'workshop2010', :to => 'welcome#workshop2010', :as => 'workshop2010'
  match 'workshop2009', :to => 'welcome#workshop2009', :as => 'workshop2009'
  match 'CNS_workshop', :to => 'welcome#CNS_workshop', :as => 'CNS_workshop'
  match 'lems_dev', :to => 'welcome#lems_dev', :as => 'lems_dev'
  match 'libnml', :to => 'welcome#libnml', :as => 'libnml'
  match 'compatibility', :to => 'welcome#compatibility', :as => 'compatibility'
  match 'specifications', :to => 'welcome#specifications', :as => 'specifications'
  match 'examples', :to => 'welcome#examples', :as => 'examples'
  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put]
  match '/issues/preview/new/:project_id', :to => 'previews#issue', :as => 'preview_new_issue', :via => [:get, :post, :put]
  match '/issues/preview/edit/:id', :to => 'previews#issue', :as => 'preview_edit_issue', :via => [:get, :post, :put]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put]

  match 'projects/:id/wiki', :to => 'wikis#edit', :via => :post
  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  match '/journals/diff/:id', :to => 'journals#diff', :id => /\d+/, :via => :get
  match '/journals/edit/:id', :to => 'journals#edit', :id => /\d+/, :via => [:get, :post]

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  match 'my/reset_rss_key', :controller => 'my', :action => 'reset_rss_key', :via => :post
  match 'my/reset_api_key', :controller => 'my', :action => 'reset_api_key', :via => :post
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/page_layout', :controller => 'my', :action => 'page_layout', :via => :get
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post

  resources :users
  match 'users/:id/memberships/:membership_id', :to => 'users#edit_membership', :via => :put, :as => 'user_membership'
  match 'users/:id/memberships/:membership_id', :to => 'users#destroy_membership', :via => :delete
  match 'users/:id/memberships', :to => 'users#edit_membership', :via => :post, :as => 'user_memberships'

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
    end

    resources :memberships, :shallow => true, :controller => 'members', :only => [:index, :show, :new, :create, :update, :destroy] do
      collection do
        get 'autocomplete'
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create] do
      resources :time_entries, :controller => 'timelog' do
        collection do
          get 'report'
        end
      end
    end
    # issue form update
    match 'issues/update_form', :controller => 'issues', :action => 'update_form', :via => [:put, :post], :as => 'issue_form'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog' do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    resources :issue_categories, :shallow => true
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    resources :repositories, :shallow => true, :except => [:index, :show] do
      member do
        match 'committers', :via => [:get, :post]
      end
    end

    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :new, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'

neuroml2_site_may1614/app/models/wiki.rb
# Redmine - project management software
# Copyright (C) 2006-2013  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class Wiki < ActiveRecord::Base
  include Redmine::SafeAttributes
  belongs_to :project
  has_many :pages, :class_name => 'WikiPage', :dependent => :destroy, :order => 'title'
  has_many :redirects, :class_name => 'WikiRedirect', :dependent => :delete_all

  acts_as_watchable

  validates_presence_of :start_page
  validates_format_of :start_page, :with => /\A[^,\.\/\?\;\|\:]*\z/

  safe_attributes 'start_page'

  def visible?(user=User.current)
    !user.nil? && user.allowed_to?(:view_wiki_pages, project)
  end

  # Returns the wiki page that acts as the sidebar content
  # or nil if no such page exists
  def sidebar
    @sidebar ||= find_page('Sidebar', :with_redirect => false)
  end

  # find the page with the given title
  # if page doesn't exist, return a new page
  def find_or_new_page(title)
    title = start_page if title.blank?
    find_page(title) || WikiPage.new(:wiki => self, :title => Wiki.titleize(title))
  end

  # find the page with the given title
  def find_page(title, options = {})
    @page_found_with_redirect = false
    title = start_page if title.blank?
    title = Wiki.titleize(title)
    page = pages.first(:conditions => ["LOWER(title) = LOWER(?)", title])
    if !page && !(options[:with_redirect] == false)
      # search for a redirect
      redirect = redirects.first(:conditions => ["LOWER(title) = LOWER(?)", title])
      if redirect
        page = find_page(redirect.redirects_to, :with_redirect => false)
        @page_found_with_redirect = true
      end
    end
    page
  end

  # Returns true if the last page was found with a redirect
  def page_found_with_redirect?
    @page_found_with_redirect
  end

  # Finds a page by title
  # The given string can be of one of the forms: "title" or "project:title"
  # Examples:
  #   Wiki.find_page("bar", project => foo)
  #   Wiki.find_page("foo:bar")
  def self.find_page(title, options = {})
    project = options[:project]
    if title.to_s =~ %r{^([^\:]+)\:(.*)$}
      project_identifier, title = $1, $2
      project = Project.find_by_identifier(project_identifier) || Project.find_by_name(project_identifier)
    end
    if project && project.wiki
      page = project.wiki.find_page(title)
      if page && page.content
        page
      end
    end
  end

  # turn a string into a valid page title
  def self.titleize(title)
    # replace spaces with _ and remove unwanted caracters
    title = title.gsub(/\s+/, '_').delete(',./?;|:') if title
    # upcase the first letter
    title = (title.slice(0..0).upcase + (title.slice(1..-1) || '')) if title
    title
  end
end

neuroml2_site_may1614/app/controllers/wikis_controller.rb
# Redmine - project management software
# Copyright (C) 2006-2013  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

class WikisController < ApplicationController
  menu_item :settings
  before_filter :find_project, :authorize

  # Create or update a project's wiki
  def edit
    @wiki = @project.wiki || Wiki.new(:project => @project)
    @wiki.safe_attributes = params[:wiki]
    @wiki.save if request.post?
  end

  # Delete a project's wiki
  def destroy
    if request.post? && params[:confirm] && @project.wiki
      @project.wiki.destroy
      redirect_to settings_project_path(@project, :tab => 'wiki')
    end
  end
end

neuroml2_site_may1614/app/helpers/wiki_helper.rb
# encoding: utf-8
#
# Redmine - project management software
# Copyright (C) 2006-2013  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module WikiHelper

  def wiki_page_options_for_select(pages, selected = nil, parent = nil, level = 0)
    pages = pages.group_by(&:parent) unless pages.is_a?(Hash)
    s = ''.html_safe
    if pages.has_key?(parent)
      pages[parent].each do |page|
        attrs = "value='#{page.id}'"
        attrs << " selected='selected'" if selected == page
        indent = (level > 0) ? ('&nbsp;' * level * 2 + '&#187; ') : ''

        s << content_tag('option', (indent + h(page.pretty_title)).html_safe, :value => page.id.to_s, :selected => selected == page) +
               wiki_page_options_for_select(pages, selected, page, level + 1)
      end
    end
    s
  end

  def wiki_page_breadcrumb(page)
    breadcrumb(page.ancestors.reverse.collect {|parent|
      link_to(h(parent.pretty_title), {:controller => 'wiki', :action => 'show', :id => parent.title, :project_id => parent.project, :version => nil})
    })
  end
end

neuroml2_site_may1614/app/views/wiki/_content.html.erb
<div class="wiki wiki-page">
  <%= textilizable content, :text, :attachments => content.page.attachments,
        :edit_section_links => (@sections_editable && {:controller => 'wiki', :action => 'edit', :project_id => @page.project, :id => @page.title}) %>
</div>

neuroml2_site_may1614/app/views/wiki/_sidebar.html.erb
<% if @wiki && @wiki.sidebar -%>
  <%= textilizable @wiki.sidebar.content, :text %>
<% end -%>

<h3><%= l(:label_wiki) %></h3>

<%= link_to l(:field_start_page), {:action => 'show', :id => nil} %><br />
<%= link_to l(:label_index_by_title), {:action => 'index'} %><br />
<%= link_to l(:label_index_by_date), {:controller => 'wiki', :project_id => @project, :action => 'date_index'} %><br />

neuroml2_site_may1614/app/views/wiki/annotate.html.erb
<div class="contextual">
<%= link_to(l(:button_edit), {:action => 'edit', :id => @page.title}, :class => 'icon icon-edit') %>
<%= link_to(l(:label_history),
            {:action => 'history', :id => @page.title}, :class => 'icon icon-history') %>
</div>

<%= wiki_page_breadcrumb(@page) %>

<h2><%=h @page.pretty_title %></h2>

<p>
<%= l(:label_version) %> <%= link_to h(@annotate.content.version),
                                     :action => 'show', :project_id => @project,
                                     :id => @page.title, :version => @annotate.content.version %>
<em>(<%= h(@annotate.content.author ?
             @annotate.content.author.name : l(:label_user_anonymous))
      %>, <%= format_time(@annotate.content.updated_on) %>)</em>
</p>

<% colors = Hash.new {|k,v| k[v] = (k.size % 12) } %>

<table class="filecontent annotate">
<tbody>
<% line_num = 1 %>
<% @annotate.lines.each do |line| -%>
<tr class="bloc-<%= colors[line[0]] %>">
    <th class="line-num"><%= line_num %></th>
    <td class="revision"><%= link_to line[0], :controller => 'wiki',
                             :action => 'show', :project_id => @project,
                             :id => @page.title, :version => line[0] %></td>
    <td class="author"><%= h(line[1]) %></td>
    <td class="line-code"><pre><%=h line[2] %></pre></td>
</tr>
<% line_num += 1 %>
<% end -%>
</tbody>
</table>

<% content_for :header_tags do %>
<%= stylesheet_link_tag 'scm' %>
<% end %>

neuroml2_site_may1614/app/views/wiki/date_index.html.erb
<div class="contextual">
<%= watcher_link(@wiki, User.current) %>
</div>

<h2><%= l(:label_index_by_date) %></h2>

<% if @pages.empty? %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<% @pages_by_date.keys.sort.reverse.each do |date| %>
<h3><%= format_date(date) %></h3>
<ul>
<% @pages_by_date[date].each do |page| %>
    <li><%= link_to h(page.pretty_title), :action => 'show', :id => page.title, :project_id => page.project %></li>
<% end %>
</ul>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>

<% unless @pages.empty? %>
<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:controller => 'activities', :action => 'index', :id => @project, :show_wiki_edits => 1, :key => User.current.rss_key} %>
  <% if User.current.allowed_to?(:export_wiki_pages, @project) %>
  <%= f.link_to('PDF', :url => {:action => 'export', :format => 'pdf'}) %>
  <%= f.link_to('HTML', :url => {:action => 'export'}) %>
  <% end %>
<% end %>
<% end %>

<% content_for :header_tags do %>
<%= auto_discovery_link_tag(:atom, :controller => 'activities', :action => 'index', :id => @project, :show_wiki_edits => 1, :format => 'atom', :key => User.current.rss_key) %>
<% end %>

neuroml2_site_may1614/app/views/wiki/destroy.html.erb
<%= wiki_page_breadcrumb(@page) %>

<h2><%=h @page.pretty_title %></h2>

<%= form_tag({}, :method => :delete) do %>
<div class="box">
<p><strong><%= l(:text_wiki_page_destroy_question, :descendants => @descendants_count) %></strong></p>
<p><label><%= radio_button_tag 'todo', 'nullify', true %> <%= l(:text_wiki_page_nullify_children) %></label><br />
<label><%= radio_button_tag 'todo', 'destroy', false %> <%= l(:text_wiki_page_destroy_children) %></label>
<% if @reassignable_to.any? %>
<br />
<label><%= radio_button_tag 'todo', 'reassign', false %> <%= l(:text_wiki_page_reassign_children) %></label>:
<%= label_tag "reassign_to_id", l(:description_wiki_subpages_reassign), :class => "hidden-for-sighted" %>
<%= select_tag 'reassign_to_id', wiki_page_options_for_select(@reassignable_to),
                                 :onclick => "$('#todo_reassign').attr('checked', true);" %>
<% end %>
</p>
</div>

<%= submit_tag l(:button_apply) %>
<%= link_to l(:button_cancel), :controller => 'wiki', :action => 'show', :project_id => @project, :id => @page.title %>
<% end %>

neuroml2_site_may1614/app/views/wiki/diff.html.erb
<div class="contextual">
<%= link_to(l(:label_history), {:action => 'history', :id => @page.title},
            :class => 'icon icon-history') %>
</div>

<%= wiki_page_breadcrumb(@page) %>

<h2><%= h(@page.pretty_title) %></h2>

<p>
<%= l(:label_version) %> <%= link_to @diff.content_from.version, :action => 'show', :id => @page.title, :project_id => @page.project, :version => @diff.content_from.version %>
<em>(<%= @diff.content_from.author ?
             @diff.content_from.author.name : l(:label_user_anonymous)
      %>, <%= format_time(@diff.content_from.updated_on) %>)</em>
&#8594;
<%= l(:label_version) %> <%= link_to @diff.content_to.version, :action => 'show',
                             :id => @page.title, :project_id => @page.project,
                             :version => @diff.content_to.version
                          %>/<%= @page.content.version %>
<em>(<%= @diff.content_to.author ?
             link_to_user(@diff.content_to.author.name) : l(:label_user_anonymous)
      %>, <%= format_time(@diff.content_to.updated_on) %>)</em>
</p>

<div class="text-diff">
<%= simple_format_without_paragraph @diff.to_html %>
</div>

neuroml2_site_may1614/app/views/wiki/edit.html.erb
<%= wiki_page_breadcrumb(@page) %>

<h2><%= h @page.pretty_title %></h2>

<%= form_for @content, :as => :content,
            :url => {:action => 'update', :id => @page.title},
            :html => {:method => :put, :multipart => true, :id => 'wiki_form'} do |f| %>
<%= f.hidden_field :version %>
<% if @section %>
<%= hidden_field_tag 'section', @section %>
<%= hidden_field_tag 'section_hash', @section_hash %>
<% end %>
<%= error_messages_for 'content' %>

<div class="box tabular">
<%= text_area_tag 'content[text]', @text, :cols => 100, :rows => 25,
                  :class => 'wiki-edit', :accesskey => accesskey(:edit) %>

<% if @page.safe_attribute_names.include?('parent_id') && @wiki.pages.any? %>
  <%= fields_for @page do |fp| %>
    <p>
      <label><%= l(:field_parent_title) %></label>
      <%= fp.select :parent_id,
                    content_tag('option', '', :value => '') +
                       wiki_page_options_for_select(@wiki.pages.all(:include => :parent) -
                         @page.self_and_descendants, @page.parent) %>
    </p>
  <% end %>
<% end %>

<p><label><%= l(:field_comments) %></label><%= f.text_field :comments, :size => 120 %></p>
<p><label><%=l(:label_attachment_plural)%></label><%= render :partial => 'attachments/form' %></p>
</div>

<p><%= submit_tag l(:button_save) %>
   <%= preview_link({:controller => 'wiki', :action => 'preview', :project_id => @project, :id => @page.title }, 'wiki_form') %></p>
<%= wikitoolbar_for 'content_text' %>
<% end %>

<div id="preview" class="wiki"></div>

<% content_for :header_tags do %>
  <%= robot_exclusion_tag %>
<% end %>

<% html_title @page.pretty_title %>

neuroml2_site_may1614/app/views/wiki/history.html.erb
<%= wiki_page_breadcrumb(@page) %>

<h2><%= h(@page.pretty_title) %></h2>

<h3><%= l(:label_history) %></h3>

<%= form_tag({:controller => 'wiki', :action => 'diff',
              :project_id => @page.project, :id => @page.title},
              :method => :get) do %>
<table class="list wiki-page-versions">
<thead><tr>
    <th>#</th>
    <th></th>
    <th></th>
    <th><%= l(:field_updated_on) %></th>
    <th><%= l(:field_author) %></th>
    <th><%= l(:field_comments) %></th>
    <th></th>
</tr></thead>
<tbody>
<% show_diff = @versions.size > 1 %>
<% line_num = 1 %>
<% @versions.each do |ver| %>
<tr class="wiki-page-version <%= cycle("odd", "even") %>">
    <td class="id"><%= link_to h(ver.version), :action => 'show', :id => @page.title, :project_id => @page.project, :version => ver.version %></td>
    <td class="checkbox"><%= radio_button_tag('version', ver.version, (line_num==1), :id => "cb-#{line_num}", :onclick => "$('#cbto-#{line_num+1}').attr('checked', true);") if show_diff && (line_num < @versions.size) %></td>
    <td class="checkbox"><%= radio_button_tag('version_from', ver.version, (line_num==2), :id => "cbto-#{line_num}") if show_diff && (line_num > 1) %></td>
    <td class="updated_on"><%= format_time(ver.updated_on) %></td>
    <td class="author"><%= link_to_user ver.author %></td>
    <td class="comments"><%=h ver.comments %></td>
    <td class="buttons">
      <%= link_to l(:button_annotate), :action => 'annotate', :id => @page.title, :version => ver.version %>
      <%= delete_link wiki_page_path(@page, :version => ver.version) if User.current.allowed_to?(:delete_wiki_pages, @page.project) && @version_count > 1 %>
    </td>
</tr>
<% line_num += 1 %>
<% end %>
</tbody>
</table>
<%= submit_tag l(:label_view_diff), :class => 'small' if show_diff %>
<span class="pagination"><%= pagination_links_full @version_pages, @version_count %></span>
<% end %>